# Generated by Django 6.0.2 on 2026-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nomina', 'Nómina'), ('proveedor', 'Proveedor'), ('servicios', 'Servicios'), ('arriendo', 'Arriendo'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], max_length=20)),
                ('beneficiario', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
