# Generated by Django 6.0.2 on 2026-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cargo',
            field=models.CharField(blank=True, choices=[('cocinero', 'Cocinero'), ('ayudante_cocina', 'Ayudante de Cocina'), ('mesero', 'Mesero'), ('pizzero', 'Pizzero'), ('domiciliario', 'Domiciliario'), ('particular', 'Particular')], max_length=50, null=True),
        ),
    ]
