# Generated by Django 6.0.2 on 2026-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('contra_entrega', 'Contra Entrega'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
