# Generated by Django 6.0.2 on 2026-02-24 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='bi-star', max_length=50, verbose_name='Icono (Clase Bootstrap Icons)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/features/', verbose_name='Imagen (Opcional)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen Externa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Servicio/Feature',
                'verbose_name_plural': 'Servicios/Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Empapados Pop', max_length=100)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, default='© 2024 Empapados Pop. Todos los derechos reservados.', null=True)),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Horarios de Atención')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(verbose_name='Subtítulo/Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/hero/', verbose_name='Imagen de Fondo')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen Externa (Cloudinary)')),
                ('button_text', models.CharField(default='Comprar ahora', max_length=50, verbose_name='Texto del Botón')),
                ('button_link', models.CharField(default='/order', max_length=200, verbose_name='Enlace del Botón')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sección Hero',
                'verbose_name_plural': 'Secciones Hero',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('client_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Rol (Opcional)')),
                ('content', models.TextField(verbose_name='Testimonio')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/testimonials/', verbose_name='Foto del Cliente')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Foto Externa')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
