# Generated by Django 6.0.2 on 2026-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('movimientos', 'Movimientos')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
